<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>
    <div class="block block-blog block-recent-posts">
        <div class="block-title">
            <strong><span><?php echo $this->__('Recent Posts') ?></span></strong>
        </div>
        <div class="block-content">
            <ul id="recent-posts" class="recent-posts">
                <?php foreach($posts as $post): ?>
                    <li class="item">
                        <a href="<?php echo $this->getPostUrl($post->getPostUrlKey()) ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>"><?php echo $this->htmlEscape($post->getPostTitle()) ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <script type="text/javascript">decorateList('recent-posts')</script>
        </div>
    </div>
<?php endif; ?>