<div class="block block-blog block-blog-search">
    <div class="block-title">
        <strong><span><?php echo $this->__('Search') ?></span></strong>
    </div>
    <div class="block-content">
        <form method="get" action="<?php echo $this->getSearchActionUrl() ?>" id="blog-search-form">
            <div class="blog-search">
                <input type="text" name="s" class="input-text required-entry" title="<?php echo $this->__('Search') ?>" value="<?php echo $this->escapeHtml($this->getSearchTerm()) ?>"/>
                <button class="button" title="<?php echo $this->__('Search') ?>" type="submit"><span><span><?php echo $this->__('Search') ?></span></span></button>
            </div>
        </form>
        <script type="text/javascript">
        //< ![CDATA[
            var searchForm = new VarienForm('blog-search-form');
        //]]>
        </script>
    </div>
</div>