<?php 
/**
 * Xcentia_Event extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Xcentia
 * @package        Xcentia_Event
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event list template
 *
 * @category    Xcentia
 * @package     Xcentia_Event
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_events = $this->getEvents(); ?>
<div class="page-title event-title">
    <h1><?php echo Mage::helper('xcentia_event')->__('Events') ?></h1>
</div>
<?php if ($_events->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="event-list-container">
    <?php foreach ($_events as $_event) : ?>
        <div class="event-list-item">
            <a href="<?php echo $_event->getEventUrl()?>">
                <?php echo $_event->getLocation();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('xcentia_event')->__('There are no events at this moment');?>
<?php endif;?>
