<?php
/**
 * MageWorx
 * MageWorx SeoReports Extension
 *
 * @category   MageWorx
 * @package    MageWorx_SeoReports
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
$modelName = Mage::registry('seosuite_template_current_model_name');
$modelId   = Mage::registry('seosuite_template_current_model_id');
?>
<style type="text/css" >
    ul { list-style-type:none; padding:0; margin:0; }
    li { margin-left:0; border:1px solid #ccc; margin:2px; padding:2px 2px 2px 2px; font:normal 12px sans-serif; }
    img { margin-right:5px; }
</style>


<ul id="processRows"></ul>

<script type="text/javascript">
    tplRowSuccess = new Template('<li style="background-color:#DDF;"><img src="<?php echo $this->getSkinUrl('images/fam_bullet_success.gif'); ?>" class="v-middle" /> #{text}</li>');
    tplRowWait = '<li class="wait"><img src="<?php echo $this->getSkinUrl('images/rule-ajax-loader.gif'); ?>" class="v-middle" /></li>';
    tplRowDone = '<li class="wait"><img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif'); ?>" class="v-middle" /> <?php echo $this->__('Done') ?></li>';

    function runProcess(data) {
        $$('.wait').each(function(el) {
            el.remove();
        });

        Element.insert($("processRows"), tplRowSuccess.evaluate(data));

        if (data.stop) {
            Element.insert($("processRows"), tplRowDone);
            window.scrollTo(0, 90000);
            return true;
        }

        Element.insert($("processRows"), tplRowWait);
        window.scrollTo(0, 9000);

        new Ajax.Request(data.url, {
            method: "get",
            onSuccess: function(transport) {
                if (transport.responseText.isJSON()) {
                    runProcess(transport.responseText.evalJSON());
                }
                else {
                    Element.insert($("processRows"), tplRowDone);
                    window.scrollTo(0, 90000);
                    window.location = transport.responseText;
                }
            }
        }
        );
    }
    runProcess({'text': '<?php echo $this->__('Starting "Apply %s". <span style="color:red">Please do not close this window.</span>',
        $modelName)
?>', 'url': '<?php echo $this->getUrl('*/*/runApply/', array('current'  => 0, 'model_id' => $modelId)) ?>'});
</script>
