<?php
$notifications = $this->getNotifications();
foreach($notifications as $noti):
?>
<div data-id="<?php echo $noti['id'];?>" class="magebirdNotification<?php if($noti['is_critical']) echo ' isCriticalNoti'?>">
  <?php echo $noti['notification'];?>
  <p class="dismissNotification" data-id="<?php echo $noti['id'];?>">Dismiss x</p>
</div>
<?php endforeach;?>
<script>
jQuery(".magebirdNotification").each(function(){
    id = jQuery(this).attr('data-id');
    if(jQuery(".magebirdNotification[data-id='"+id+"']").length>1){
      jQuery(".magebirdNotification[data-id='"+id+"']").not(':first').remove();  
    }  
});

jQuery(".dismissNotification").click(function(){
    var $this = jQuery(this);
    $this.text('Dismissing...');
    var id = jQuery(this).attr('data-id');
    jQuery.ajax({    
      type: "POST",
      url: "<?php echo $this->getUrl('*/magebird_popup/dismissNotification');?>?isAjax=true",
      data:'id='+id+'&form_key='+window.FORM_KEY,
      success: function(response){      
        if(response.success=='false'){
          alert(response.error)
        }else{
          console.log($this.parent()[0].outerHTML)
          $this.parent().fadeOut();                 
        }          
      }
    });
  
});
</script>