<?php  
/*
 * Adding javascript include
 */
if ('front' != Mage::app()->getRequest()->getControllerName()) {
    ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/FME/fme_layered_nav.js"></script> 
    <?php
}
?>

<?php if ($this->canShowBlock()): $state = $this->getStateInfo() ?>
    
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->canShowOptions()): ?>
                <?php
                //echo "<pre>";
                //print_r($state);
                ?>
                <div class="fme-filter">
                    <input type="hidden" id="fme_layered_url" value="<?php echo $this->htmlEscape($state[0]) ?>"/>
                    <input type="hidden" id="fme_layered_params" value="<?php echo $this->htmlEscape($state[1]) ?>"/> 
                    <input type="hidden" id="fme_layered_ajax" value="<?php echo $this->htmlEscape($state[2]) ?>"/> 
                    <div id="fme_filters_list">
                      

                        <?php $_filters = $this->getFilters() ?>
                         <section class="firstSection">
						<?php foreach ($_filters as $_filter): ?>
                            <?php if ($_filter->getItemsCount()): ?>
                            
							<div class="listHeading">
							  
										
											<h2><?php echo $this->__($_filter->getName()) ?></h2>
												<?php if ($clearUrl = $_filter->getClearUrl()): ?>
												  
												<?php /* <a id="<?php echo $_filter->getVar() ?>-clear" <?php if (!$this->getIsRemoveLinks()): ?>href="<?php echo $this->htmlEscape($clearUrl) ?>" <?php endif; ?> class="btn-remove fme_layered_clear right" title="<?php echo $this->__('Remove This Item') ?>">
												<?php echo $this->__('Remove This Item') ?>
												</a> */ ?>
											 
											 
											<?php endif ?>
							</div><!-- listHeading end -->
							 
							<div class="lists">	 
								 <?php echo $_filter->getHtml() ?>
								 
							</div>	 
                            <?php endif; ?>
                        <?php endforeach; ?>
                          <?php if ($state[1] AND $this->bNeedClearAll()): ?>
                            <div class="actions fme_layered_clear_all">
                                <?php /*?><a class="fme_layered_clearall" href="<?php echo $this->htmlEscape($this->getClearAllUrl()) ?>"><?php echo $this->__('Clear All') ?>
                                </a><?php */?>
                                <a class="fme_layered_clearall" onclick="clearAllFilter()" href="javascript:void(0);"><?php echo $this->__('Clear All') ?>
                                </a>
                            </div>            
                        <?php endif  ?> 
							 
							
						  </section>   
                               
                                
                                
                               
                    </div>
                    <script type="text/javascript">
                        decorateDataList('narrow-by-list');
                        fme_layered_init();
                    </script>
                </div>
            <?php endif; ?>
        
        <div class="fme_loading_filters" style="display:none"></div>
    
<?php endif; ?>

<script type="text/javascript">
    fme_layered_init();
</script>