<?php
if ($this->horizontalShareEnable() == "1" && $this->horizontalShareSuccess() == "1") {
    if (trim($this->sharingTitle()) != "") {
        echo '<div style="font-weight:bold; clear: both;">' . trim($this->sharingTitle()) . '</div>';
    }
    echo '<div class="loginRadiusHorizontalSharing"></div>';
}
if ($this->verticalShareEnable() == "1" && $this->verticalShareSuccess() == "1") {
    echo '<div class="loginRadiusVerticalSharing"></div>';
}
?>