<?php
/**
 * MageWorx
 * MageWorx XSitemap Extension
 *
 * @category   MageWorx
 * @package    MageWorx_XSitemap
 * @copyright  Copyright (c) 2016 MageWorx (http://www.mageworx.com/)
 */
?>
<br/>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <h3><a href = "<?php echo Mage::helper('adminhtml')->getUrl('*/mageworx_xsitemap/index/') ?>"><?php echo $this->__('Warning: After you Flush Images Cache, re-generate XML sitemap.') ?></a></h3>
        </td>
    </tr>
</table>